version: '3.6'
services:
  domserver:
    image: "domjudge/domserver"
    environment:
      MYSQL_HOST: "db"
      MYSQL_USER: "domjudge"
      MYSQL_PASSWORD: "${DB_PASS}"
      MYSQL_DATABASE: "domjudge"
      DJ_DB_INSTALL_BARE: "0"
      MYSQL_ROOT_PASSWORD: "${DB_PASS}"
    depends_on:
      - "db"
    ports:
      - target: 80
        published: ${PORT}
        protocol: tcp
        mode: ${MODE}

    deploy:
      restart_policy:
        condition: on-failure
  judge:
    image: "domjudge/judgehost"
    environment:
      DAEMON_ID: "{{.Task.Slot}}"
      DOMSERVER_BASEURL: "http://domserver/"
      JUDGEDAEMON_USERNAME: "judgehost"
      JUDGEDAEMON_PASSWORD: "${JUDGE_PASS}"
    depends_on:
      - "domserver"
    hostname: "jh-{{.Task.Slot}}"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    tmpfs:
      - "/run"
      - "/tmp"
    deploy:
      restart_policy:
        condition: on-failure
  db:
    image: "mariadb"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASS}"
      MYSQL_DATABASE: "domjudge"
      MYSQL_USER: "domjudge"
      MYSQL_PASSWORD: "${DB_PASS}"
    volumes:
      - ~/data:/var/lib/mysql
    deploy:
      restart_policy:
        condition: on-failure